### ISSUE TITLE
Block: there is only one `render.php` instead of two

### ISSUE THREAD

**Issue by renatonascalves** [alleyinteractive/create-wordpress-plugin#139]
Currently there is one for development and another in the `build` folder. Since this is how `@wordpress/create-block` is setup, not sure how we would do that, but sharing here as an idea.

**Comment by stevenslack** [comment]
@renatonascalves The `render.php` file in the blocks directory will be copied during the build process using the `copy-webpack-plugin` and read via the `block.json` from the build directory. The only file that gets read is the built one, but it is a copy. 

The best way to have these changes seen is by running the `start` script running so that the build happens when you make changes. The files in the build directory are read by the `load_scripts` function in `src/assets.php` https://github.com/alleyinteractive/create-wordpress-plugin/blob/develop/src/assets.php#L199-L208

**Comment by renatonascalves** [comment]
I'm aware. My meaning is there are two files with the same name in a project. I accidentally was editing the "wrong" `render.php` (since they are the same name) file.

I think one needs to be extra careful when choosing a `render.php` file for edition (in VSCode for example). This is also different from previous approaches in `wp-starter-plugin`, for example, where only one template part for a block was available.

**Comment by renatonascalves** [comment]
I think it is unlikely this might be an easy fix. Feel free to close this issue unless I'm wrong.
